### ISSUE TITLE
Méthode de comparaison des scores

### ISSUE THREAD

**Issue by alainds** [InseeFrLab/AdventOfCodeLeaderboard#18]
Ce serait bien que la méthode de comparaison des scores (dans la methode getMembersList de UserList.java) tienne compte en priorité des étoiles et ensuite du score. 
Pour l'instant ça prend uniquement le score.

**Comment by olevitt** [comment]
👍 
On pourrait envisager de mettre en paramètre le mode de classement utilisé.  
Mais on veut supporter étoiles puis score plutôt que score. Ca met moins de pression et met plutôt l'accent sur le fait de faire les programmes.  

PR bienvenues :)
